#! configuration/local.yaml
application:
  host: 127.0.0.1
  base_url: "http://127.0.0.1"
database:
  require_ssl: false

email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "krongkaew@enres.co"
  authorization_token: "d72be1ae-eb0d-4a4b-afe8-00e59af10299"
