application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "krongkaew@enres.co"
  authorization_token: "d72be1ae-eb0d-4a4b-afe8-00e59af10299"
  timeout_milliseconds: 10000
